spring:
  application:
    name: order
  datasource:
    url: jdbc:h2:mem:order
    driverClassName: org.h2.Driver
    username: fulfillment
    password: password
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  artemis:
    mode: native
    broker-url: tcp://localhost:8161
    user: admin
    password: admin
  jms:
    pub-sub-domain: false

server:
  port: 8083

fulfillment:
  application:
    jms:
      receive:
        order:
          topic: ORDER.QUEUE
