spring:
  application:
    name: fulfillment
  datasource:
    url: jdbc:h2:mem:fulfillment
    driverClassName: org.h2.Driver
    username: fulfillment
    password: password
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  artemis:
    broker-url: tcp://localhost:61616
    mode: native
    user: artemis
    password: artemis
  jms:
    pub-sub-domain: true

server:
  port: 8083

activate:
  listener: true

fulfillment:
  application:
    jms:
      listener:
        order:
          topic: ORDER