spring:
  application:
    name: order
  datasource:
    url: jdbc:h2:mem:order
    driverClassName: org.h2.Driver
    username: order
    password: password
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  artemis:
    broker-url: tcp://localhost:61616
    mode: native
    user: artemis
    password: artemis
  jms:
    pub-sub-domain: true

server:
    port: 8082

order:
  application:
    jms:
      producer:
        order:
          delivery-persistent: true
          session-transacted: true
          default-topic: ORDER